package com.example.tickets.ai.ask;

import static com.example.tickets.common.Texts.strip;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import java.util.List;

public final class AskDtos {

    /** Fixed text: the no-match answer is never generated by the LLM. */
    public static final String NO_MATCH_MESSAGE = "No relevant tickets found. I can only answer questions using our "
            + "support ticket history, and no ticket matches this question.";

    private AskDtos() {
    }

    /** {@code question} is validated after trimming (FR-24). */
    public record AskRequest(@NotBlank @Size(min = 3, max = 500) String question) {
        public AskRequest {
            question = strip(question);
        }
    }

    public record AskResponse(
            String question,
            boolean grounded,
            String answer,
            List<Citation> citations,
            NoMatchReason noMatchReason,
            Retrieval retrieval) {
    }

    public record Citation(String ticketId, String title, String status) {
    }

    public record Retrieval(int topK, double similarityThreshold, String filter, List<Match> matches) {
    }

    public record Match(String ticketId, String chunkType, double score) {
    }
}
